### ISSUE TITLE
Automatic Light/Dark Theme

### ISSUE THREAD

**Issue by alichraghi** [hexops/hexops.com#2]
reading white papers at day feels better than dark (at least for me 🙄).
we can provide a light theme without JS (buttons) like many websites that change theme automatically with `@media (prefers-color-scheme: light/dark)`

applies to all hexops websites
- [x] [hexops.com](https://hexops.com/)
- [x] [devlog.hexops.com](https://devlog.hexops.com/)
- [x] [zigmonthly.org](https://zigmonthly.org/)
- [x] [machengine.org](https://machengine.org/)

**Comment by slimsag** [comment]
Absolutely agree, thanks for filing. I want to have this, I just haven't had a chance to choose good colors / test the CSS.
