### ISSUE TITLE
Page not found: opendata server

### ISSUE THREAD

**Issue by BratishkaErik** [hexops/hexops.com#3]
From https://hexops.com/privacy/:

> You can view 100% of our web analytics at [opendata.hexops.com](https://opendata.hexops.com/hexops.com).

This page returns 404: Not Found error code.

![Screenshot_20220605-232915_Fennec](https://user-images.githubusercontent.com/25210740/172062795-abea5331-9894-4b04-84d0-77138ac91f38.jpg)

**Comment by slimsag** [comment]
Whoops, looks like that website wasn't set to public by accident. I fixed it just now, all of these URLs should work now:

* https://opendata.hexops.com/hexops.com
* https://opendata.hexops.com/machengine.org
* https://opendata.hexops.com/devlog.hexops.com
* https://opendata.hexops.com/slimsag.com
* https://opendata.hexops.com/zigmonthly.org
